version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ti_informa
    ports:
      - "3307:3306" # porta 3307 no host → 3306 no container

    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: frontend-app
    restart: always
    environment:
      VITE_API_URL: http://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
